checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - src/wormling/phparia/Tests/*
        - src/wormling/phparia/Examples/*
        - vendor/*

tools:
    external_code_coverage: true
