checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - src/wormling/phparia/Tests/*

tools:
    external_code_coverage: true

build:
    tests:
        override:
            -
                coverage:
                command: phpunit --coverage-clover=coverage.clover
                    file: 'coverage.clover'
                    format: 'php-clover'