# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
#  - 5.4
#  - 5.5
  - 5.6
#  - 7.0

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - phpunit --configuration phpunit.xml --coverage-text

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email: "wormling@gmail.com"